export const translationsAz = {
	'Login': 'Giriş',
	'Sign up': 'Qeydiyyatdan keçin',
	'Sign in': 'Giriş edin',
	'Register': 'Qeydiyyat',
	'Password': 'Şifrə',
	'Password repetition': 'Şifrə təkrarı',
	'Forgot your password?': 'Şifrənizi unutmusunuz?',
	'Or continue with': 'və ya',
	'Do not have an account?': 'Hesabınız yoxdur?',
	'Do have an account?': 'Hesabınız var?',
	'By clicking continue, you agree to our Terms of Service and Privacy Policy.': 'Tıklayarak davam edin, xidmət şərtlərimizi və Məxfilik Siyasətimizi qəbul edirsiniz.',
	'Log out': 'Çıxış',
	'Notifications': 'Bildirişlər',
	'Billing': 'Ödənişlər',
	'Account': 'Hesab',
	'Change password': '',
	'Profile settings': '',
	'Language': '',
	'Country': '',
	'City': '',
	'Name': '',
	'Surname': '',
	'About': '',
	'Save': 'Yadda saxla',
	'Phone number': '',
	'Name': '',
	'Name': '',
	'Name': '',
	'Name': '',
};

